name: musicgrab-pro
services:
  - name: app
    ports:
      - port: 8000
        http_path: /
    scopes:
      - run
    routes:
      - path: /
    instances:
      type: nano
    health_checks:
      http:
        path: /
        port: 8000
        scheme: HTTP
    env:
      - name: PORT
        value: "8000"
